/// Flutter icons Reader
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Reader
///      fonts:
///       - asset: fonts/Reader.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class ReaderIcons {
  ReaderIcons._();

  static const _kFontFam = 'ReaderIcons';
  static const _kFontPkg = null;

  static const IconData battery_0 = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_25 = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_50 = IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_75 = IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_100 = IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_chagring = IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
