/// Flutter icons BatteryIcon
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BatteryIcon
///      fonts:
///       - asset: fonts/BatteryIcon.ttf
///
///
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class BatteryIcons {
  BatteryIcons._();

  static const _kFontFam = 'BatteryIcon';

  static const IconData charging = const IconData(0xf1e6, fontFamily: _kFontFam);
  static const IconData battery_full = const IconData(0xf240, fontFamily: _kFontFam);
  static const IconData battery_75 = const IconData(0xf241, fontFamily: _kFontFam);
  static const IconData battery_50 = const IconData(0xf242, fontFamily: _kFontFam);
  static const IconData battery_25 = const IconData(0xf243, fontFamily: _kFontFam);
  static const IconData battery_0 = const IconData(0xf244, fontFamily: _kFontFam);
}
